# Generated by Django 4.2.1 on 2023-05-31 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computers', '0002_computer_delete_timeperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(help_text='Формат: XX:XX', max_length=5, verbose_name='Время')),
                ('status', models.CharField(choices=[('B', 'Забронировано'), ('F', 'Свободно'), ('TB', 'Перерыв между бронями')], default='F', max_length=2, verbose_name='Статус временного промежутка')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.computer', verbose_name='Компьютер')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.CharField(help_text='Формат: XX:XX', max_length=5, verbose_name='Время начала сеанса')),
                ('time_end', models.CharField(help_text='Формат: XX:XX', max_length=5, verbose_name='Время окончания сеанса')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.computer', verbose_name='Компьютер')),
            ],
        ),
    ]
