# Generated by Django 4.2.1 on 2023-05-31 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_computer_delete_timeperiod'),
        ('booking', '0002_remove_timeperiods_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiods',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.computer', verbose_name='Компьютер'),
        ),
    ]
