# Generated by Django 4.2.1 on 2023-05-31 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_computer_delete_timeperiod'),
        ('booking', '0003_timeperiods_computer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimePeriods',
            new_name='TimePeriod',
        ),
    ]
