# Generated by Django 4.2.1 on 2023-06-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_computer_delete_timeperiod'),
        ('booking', '0004_rename_timeperiods_timeperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='computers.computer', verbose_name='Компьютер'),
        ),
        migrations.AlterField(
            model_name='timeperiod',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_periods', to='computers.computer', verbose_name='Компьютер'),
        ),
    ]
