# Generated by Django 4.2.1 on 2023-05-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.CharField(help_text='Формат: XX:XX', max_length=5, verbose_name='Время начала сеанса')),
                ('time_end', models.CharField(help_text='Формат: XX:XX', max_length=5, verbose_name='Время окончания сеанса')),
            ],
        ),
    ]
