# Generated by Django 4.2.1 on 2023-06-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время уведомления')),
                ('text', models.TextField(verbose_name='Текст уведомления')),
                ('user_vk_id', models.IntegerField(verbose_name='VK ID пользователя, которому будет отправлено уведомление.')),
                ('type', models.CharField(choices=[('NS', 'No status'), ('RTC', 'Remind to take a computer'), ('AC', 'Check if user at the computer'), ('EW', 'Warning about end of the session.')], default='NS', max_length=5)),
                ('status', models.CharField(choices=[('W', 'Awaiting to be sent'), ('NTS', 'Should already be sent.'), ('S', 'Already sent')], default='W', max_length=5, verbose_name='Статус уведомления')),
            ],
        ),
    ]
