# Generated by Django 4.2.1 on 2023-06-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('W', 'Ожидает отправки'), ('NTS', 'Should already be sent.'), ('S', 'Already sent')], default='W', max_length=5, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NS', 'No status'), ('RTC', 'Remind to take a computer'), ('AC', 'Check if user at the computer'), ('EW', 'Warning about end of the session.')], default='NS', max_length=5, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_vk_id',
            field=models.IntegerField(verbose_name='VK ID пользователя, которому будет отправлено уведомление'),
        ),
    ]
