# Generated by Django 4.2.1 on 2023-06-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NS', 'Без типа'), ('RTC', 'Напоминание о брони.'), ('AC', 'Проверка, находится ли пользователь за компьютером.'), ('EW', 'Предупреждение о конце сессии.'), ('ES', 'Конец сессии.')], default='NS', max_length=5, verbose_name='Тип'),
        ),
    ]
